### ISSUE TITLE
sparkmonitor - AttributeError: 'ScalaMonitor' object has no attribute 'comm'

### ISSUE THREAD

**Issue by itayB** [swan-cern/jupyter-extensions#103]
Hi,

First of all, this extension looks amazing - I really want to try it!
I [found](https://pypi.org/search/?q=sparkmonitor) a lot of variants of sparkmonitor extension:
![image](https://user-images.githubusercontent.com/457191/108389999-e31c5b00-7218-11eb-9d35-2f520038c74f.png)

but it seems that only [this](https://pypi.org/project/sparkmonitor/) one supports Spark 3; all others requirements explicitly declare that:

> pyspark 2.X.X or older (pyspark 3.X is currently not supported)

and this one declares that:

> PySpark on Apache Spark version 2.1.1 or higher

 
I created an image with jupyterlab and sparkmonitor extension with all requirements:
JupyterLab >= 2.0 (I've installed 2.2.9)
PySpark on Apache Spark version 2.1.1 or higher (I've installed pyspark==3.0.1)
Jupyter Notebook version 4.4.0 or higher (I've installed 6.2.0)
SBT to compile the Scala listener (I've installed 0.13.15)

I am running my jupyter lab in Kubernetes with Spark on Kubernetes:

![image](https://user-images.githubusercontent.com/457191/108392105-0b0cbe00-721b-11eb-9ec9-92ba3eb22ab9.png)

As you can see above I'm getting the result and I also see that two executors are running and finish successfully.
I found [this](https://github.com/itsjafer/jupyterlab-sparkmonitor/issues/16) issue that looks related, but it is another fork that doesn't support Spark3 (not sure if related).
 
## Additional Information
I'm adding below some additional information, I hope someone can give me a clue - I will be very happy to use this extension!

### Jupyter info within the jupyter container
```
# jupyter --version
jupyter core     : 4.7.1
jupyter-notebook : 6.2.0
qtconsole        : not installed
ipython          : 7.20.0
ipykernel        : 5.4.3
jupyter client   : 6.1.11
jupyter lab      : 2.2.9
nbconvert        : 6.0.7
ipywidgets       : not installed
nbformat         : 5.1.2
traitlets        : 5.0.5
```

### Jupyter container logs
```
[I 16:35:12.754 LabApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
[W 16:35:12.921 LabApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
[I 16:35:13.805 LabApp] JupyterLab extension loaded from /usr/local/lib/python3.7/dist-packages/jupyterlab
[I 16:35:13.805 LabApp] JupyterLab application directory is /usr/local/share/jupyter/lab
[I 16:35:13.847 SparkMonitorServer] Loading Server Extension
[I 16:35:13.847 LabApp] Serving notebooks from local directory: /opt/workspace
[I 16:35:13.847 LabApp] Jupyter Notebook 6.2.0 is running at:
[I 16:35:13.847 LabApp] http://jupyter-86bcf49699-wd4vh:8888/
[I 16:35:13.848 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 16:35:36.687 LabApp] 404 GET /api/kernels/3592066b-439e-491e-a687-54a63b8aae2a/channels?session_id=65597bad-da08-435e-9959-14efba572fd5 (127.0.0.1): Kernel doe
s not exist: 3592066b-439e-491e-a687-54a63b8aae2a
[W 16:35:36.694 LabApp] 404 GET /api/kernels/3592066b-439e-491e-a687-54a63b8aae2a/channels?session_id=65597bad-da08-435e-9959-14efba572fd5 (127.0.0.1) 8.390000ms
referer=None
[W 16:35:43.738 LabApp] Replacing stale connection: 3592066b-439e-491e-a687-54a63b8aae2a:65597bad-da08-435e-9959-14efba572fd5
[W 16:35:44.970 LabApp] 404 GET /api/kernels/3592066b-439e-491e-a687-54a63b8aae2a/channels?session_id=d3e5066f-9517-4079-8daf-28f109c5e468 (127.0.0.1): Kernel doe
s not exist: 3592066b-439e-491e-a687-54a63b8aae2a
[W 16:35:44.971 LabApp] 404 GET /api/kernels/3592066b-439e-491e-a687-54a63b8aae2a/channels?session_id=d3e5066f-9517-4079-8daf-28f109c5e468 (127.0.0.1) 2.070000ms
referer=None
[W 16:35:50.860 LabApp] Replacing stale connection: 3592066b-439e-491e-a687-54a63b8aae2a:d3e5066f-9517-4079-8daf-28f109c5e468
[I 16:36:26.617 LabApp] 302 GET / (127.0.0.1) 0.440000ms
[W 16:36:27.455 LabApp] 403 GET /metrics?1613666187426 (127.0.0.1) 1.120000ms referer=http://localhost:8888/lab?
[I 16:36:29.256 LabApp] Build is up to date
[W 16:36:30.273 LabApp] Failed to fetch package metadata for '@swan-cern/sparkmonitor': <HTTPError 404: 'Not Found'>
[W 16:36:32.469 LabApp] 403 GET /metrics?1613666192435 (127.0.0.1) 1.350000ms referer=http://localhost:8888/lab?
[I 16:36:36.755 LabApp] Creating new notebook in
[I 16:36:36.764 LabApp] Writing notebook-signing key to /root/.local/share/jupyter/notebook_secret
[I 16:36:37.213 LabApp] Kernel started: bcb04515-1cf9-4dc3-beda-8be8badaeb7d, name: python3
[W 16:36:37.483 LabApp] 403 GET /metrics?1613666197443 (127.0.0.1) 1.300000ms referer=http://localhost:8888/lab?
INFO:SparkMonitorKernel:Starting Kernel Extension
INFO:SparkMonitorKernel:Socket Listening on port 47571
INFO:SparkMonitorKernel:Starting socket thread, going to accept
INFO:SparkMonitorKernel:SparkConf Configured, Starting to listen on port: 47571
INFO:SparkMonitorKernel:47571
INFO:SparkMonitorKernel:Adding jar from /usr/local/lib/python3.7/dist-packages/sparkmonitor/listener_2.12.jar
[W 16:36:42.463 LabApp] 403 GET /metrics?1613666202451 (127.0.0.1) 1.310000ms referer=http://localhost:8888/lab?
[W 16:36:47.476 LabApp] 403 GET /metrics?1613666207459 (127.0.0.1) 1.090000ms referer=http://localhost:8888/lab?
[W 16:36:52.491 LabApp] 403 GET /metrics?1613666212468 (127.0.0.1) 1.350000ms referer=http://localhost:8888/lab?
[W 16:36:57.507 LabApp] 403 GET /metrics?1613666217477 (127.0.0.1) 1.410000ms referer=http://localhost:8888/lab?
[W 16:37:02.522 LabApp] 403 GET /metrics?1613666222487 (127.0.0.1) 1.360000ms referer=http://localhost:8888/lab?
21/02/18 16:37:04 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[W 16:37:07.537 LabApp] 403 GET /metrics?1613666227497 (127.0.0.1) 1.150000ms referer=http://localhost:8888/lab?
INFO:SparkMonitorKernel:Client Connected ('127.0.0.1', 50528)
[W 16:37:12.517 LabApp] 403 GET /metrics?1613666232506 (127.0.0.1) 1.350000ms referer=http://localhost:8888/lab?
21/02/18 16:37:13 ERROR JupyterSparkMonitorListener: Exception sending socket message:
java.net.SocketException: Broken pipe (Write failed)
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
        at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
        at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at sparkmonitor.listener.JupyterSparkMonitorListener.send(CustomListener.scala:55)
        at sparkmonitor.listener.JupyterSparkMonitorListener.onExecutorAdded(CustomListener.scala:659)
        at org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:63)
        at org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28)
        at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
        at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
        at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:115)
        at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:99)
        at org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105)
        at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105)
        at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100)
        at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96)
        at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1319)
        at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96)
```

* Is the 403 `/metrics` request related?
* is the `Failed to fetch package metadata for '@swan-cern/sparkmonitor': <HTTPError 404: 'Not Found'>` related? (seems like it started only after I am triggering my code)

### Jupyter Dockerfile
```
FROM openjdk:8-jdk

ARG shared_workspace=/opt/workspace
RUN mkdir -p ${shared_workspace}

# SBT installation
ENV SBT_VERSION=0.13.15
RUN apt update && apt install -y --no-install-recommends equivs; \
        rm -rf /var/lib/apt/lists/*
COPY openjdk-8-jdk.control /tmp/
RUN cd /tmp/ && equivs-build /tmp/openjdk-8-jdk.control; \
        curl -L -o sbt-$SBT_VERSION.deb http://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb; \
        dpkg -i openjdk-8-jdk_8u212-*.deb; \
        dpkg -i sbt-$SBT_VERSION.deb

# Python3 installation
RUN apt update && \
  apt-get install -y python3 python3-setuptools python3-pip nodejs npm && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*


ENV SHARED_WORKSPACE=${shared_workspace}
VOLUME ${shared_workspace}

ARG spark_version=3.0.1

# python packages installation
RUN pip3 install --upgrade pip
RUN pip3 install \
    pyspark==${spark_version} \
    jupyterlab==2.2.9 \
    findspark==1.4.2 \
    sparkmonitor==1.1.1 \
    py4j>=0.10.9

# sparkmonitor installation
RUN \
jupyter nbextension install sparkmonitor --py && \
jupyter nbextension enable  sparkmonitor --py && \
jupyter serverextension enable --py --system sparkmonitor && \
jupyter lab build && \
ipython profile create && \
echo "c.InteractiveShellApp.extensions.append('sparkmonitor.kernelextension')" >>  $(ipython profile locate default)/ipython_kernel_config.py
RUN ln -sf /usr/local/openjdk-8/bin/java /usr/bin/java

EXPOSE 8888
WORKDIR ${SHARED_WORKSPACE}
CMD jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --LabApp.token='' --LabApp.disable_check_xsrf=True
```

Any assistant will be very appreciated!
Thanks

**Comment by itayB** [comment]
I managed to work with the widget in the Jupyter notebook (and not lab) and using the `swan_spark_conf` conf.

**Comment by diocas** [comment]
Hi @itayB we haven't migrated to Jupyterlab yet.. We only have the boilerplate for the extension in the repo, but without functionality. This should be implemented in the coming months.

@krishnan-r can you help with the other questions?

**Comment by itayB** [comment]
I fixed all issues and wrote about it here: https://towardsdatascience.com/jupyter-notebook-spark-on-kubernetes-880af7e06351

Thanks for your great widget!

**Comment by authentic7** [comment]
Hi, had the same error with sparkmonitor extension.

 monitor.send(msg)
  File "/opt/python_envs/sparkmonitor/lib/python3.7/site-packages/sparkmonitor/kernelextension.py", line 47, in send
    self.comm.send(msg)
**AttributeError: 'ScalaMonitor' object has no attribute 'comm'**

Pls help to solve the issue!!!

My installations:
 
print(swan_spark_conf.toDebugString())
spark.extraListeners=sparkmonitor.listener.JupyterSparkMonitorListener
spark.driver.extraClassPath=/opt/python_envs/sparkmonitor/lib/python3.7/site-packages/sparkmonitor/listener_2.12.jar

pyspark version: 3.0.1
jupyter core     : 4.6.3
jupyter-notebook : 6.1.4
qtconsole        : 4.7.7
ipython          : 7.18.1
ipykernel        : 5.3.4
jupyter client   : 6.1.6
jupyter lab      : 2.2.6
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 5.0.7
traitlets        : 4.3.3

 

> jupyter labextension list:

JupyterLab v2.2.6
Known labextensions:
   app dir: /opt/python_envs/sparkmonitor/share/jupyter/lab
        @swan-cern/sparkmonitor v1.1.1  enabled  OK

> jupyter serverextension list :

config dir: /root/.jupyter
    sparkmonitor.serverextension  enabled 
    - Validating...
      sparkmonitor.serverextension  OK
config dir: /opt/python_envs/sparkmonitor/etc/jupyter
    ipyparallel.nbextension  enabled 
    - Validating...
      ipyparallel.nbextension  OK
    jupyterlab  enabled 
    - Validating...
      jupyterlab 2.2.6 OK
    sparkmonitor  enabled 
    **- Validating...
      X is sparkmonitor importable?**
    jupyter_nbextensions_configurator  enabled 
    - Validating...
      jupyter_nbextensions_configurator 0.4.1 OK
    sparkmonitor.serverextension  enabled 
    - Validating...
      sparkmonitor.serverextension  OK
config dir: /usr/local/etc/jupyter
    sparkmonitor.serverextension  enabled 
    - Validating...
      sparkmonitor.serverextension  OK

>  jupyter nbextension list

Known nbextensions:
  config dir: /root/.jupyter/nbconfig
    notebook section
      sparkmonitor/extension  enabled 
      - Validating: OK
  config dir: /opt/python_envs/sparkmonitor/etc/jupyter/nbconfig
    notebook section
      plotlywidget/extension  enabled 
      - Validating: OK
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
      nbextensions_configurator/config_menu/main  enabled 
      - Validating: problems found:
        - require?  X nbextensions_configurator/config_menu/main
      arcgis/extension  enabled 
      - Validating: OK
    tree section
      ipyparallel/main  enabled 
      - Validating: OK
      nbextensions_configurator/tree_tab/main  enabled 
      - Validating: problems found:
        **- require?  X nbextensions_configurator/tree_tab/main**

**Comment by itayB** [comment]
@authentic7 are you using the `swan_spark_conf`?
```
SparkSession.builder.appName(app_name).config(conf= swan_spark_conf).getOrCreate()
```
Are you using Jupyter **notebook** (and not lab)?

**Comment by authentic7** [comment]
Thanks for your response!
Im using  jupyter-notebook : 6.1.4
![Screenshot from 2021-04-01 12-31-25](https://user-images.githubusercontent.com/17597546/113252976-620bb580-92e6-11eb-956f-d41ef13d12f4.png)

**Comment by itayB** [comment]
before I even open my Jupyter notebook I see the log:
```
[I 07:02:06.465 SparkMonitorServer] Loading Server Extension
```

after I open my browser and create a new notebook I see in the logs (before running):
```
INFO:SparkMonitorKernel:Starting Kernel Extension
INFO:SparkMonitorKernel:Socket Listening on port 42633
INFO:SparkMonitorKernel:Starting socket thread, going to accept
INFO:SparkMonitorKernel:SparkConf Configured, Starting to listen on port: 42633
INFO:SparkMonitorKernel:42633
INFO:SparkMonitorKernel:Adding jar from /opt/conda/lib/python3.8/site-packages/sparkmonitor/listener_2.12.jar
INFO:SparkMonitorKernel:Comm opened
```

Do you see those as well?

**Comment by authentic7** [comment]
@itayB  I have an error
./start_spark3_notebook.sh 
[I 13:06:10.855 NotebookApp] The port 8888 is already in use, trying another port.
[I 13:06:10.855 NotebookApp] The port 8889 is already in use, trying another port.
[I 13:06:10.890 NotebookApp] Loading IPython parallel extension
[I 13:06:10.925 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.4.1
[I 13:06:11.073 NotebookApp] JupyterLab extension loaded from /opt/bigdata/anaconda3/lib/python3.7/site-packages/jupyterlab
[I 13:06:11.073 NotebookApp] JupyterLab application directory is /opt/bigdata/anaconda3/share/jupyter/lab
[W 13:06:11.076 NotebookApp] Error loading server extension sparkmonitor.serverextension
    Traceback (most recent call last):
      File "/opt/bigdata/anaconda3/lib/python3.7/site-packages/notebook/notebookapp.py", line 1942, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/opt/bigdata/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
      File "<frozen importlib._bootstrap>", line 983, in _find_and_load
      File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
      File "<frozen importlib._bootstrap>", line 983, in _find_and_load
      File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
    **ModuleNotFoundError: No module named 'sparkmonitor'**
[I 13:06:11.078 NotebookApp] Serving notebooks from local directory:

**Comment by itayB** [comment]
From your screenshot above I see that you are using `findspark`.
I tried that approach as well and it didn't work for me. Assuming you're using `sparkmonitor==1.1.1` you should let the extension find your spark alone (AFAIR) and you should be able to print the conf in an empty notebook:
```
print(swan_spark_conf.toDebugString())
```
You can see that the extension tries to [import pyspark](https://github.com/swan-cern/jupyter-extensions/blob/master/SparkMonitor/sparkmonitor/kernelextension.py#L21) (so you can try it on an empty notebook as well) and only if it succeeds [it will create](https://github.com/swan-cern/jupyter-extensions/blob/master/SparkMonitor/sparkmonitor/kernelextension.py#L164) the conf for you.


I also see that the following log is missing in your output:
```
INFO:SparkMonitorKernel:Comm opened
```
I will guess that it's related to the block port (but I'm not sure):
```
"spark.driver.blockManager.port": "7777"
```
Did you check out [my post](https://towardsdatascience.com/jupyter-notebook-spark-on-kubernetes-880af7e06351)? you can see the `Dockerfile` for installation and  the notebook code

**Comment by authentic7** [comment]
Hi, @itayB 
Is it ok that i see 
jupyter serverextension list
**sparkmonitor  enabled 
    - Validating...
      X is sparkmonitor importable?**
jupyter nbextension list
**- Validating: problems found:
        - require?  X nbextensions_configurator/tree_tab/main**
I tried an example:
from pyspark import SparkContext
sc = SparkContext.getOrCreate(conf=swan_spark_conf) #Start the spark context
rdd = sc.parallelize([1, 2, 4, 8])

The same error!

**Comment by itayB** [comment]
> Hi, @itayB
> Is it ok that i see
> jupyter serverextension list
> **sparkmonitor enabled - Validating... X is sparkmonitor importable?**
> jupyter nbextension list
> **- Validating: problems found: - require? X nbextensions_configurator/tree_tab/main**
> I tried an example:
> from pyspark import SparkContext
> sc = SparkContext.getOrCreate(conf=swan_spark_conf) #Start the spark context
> rdd = sc.parallelize([1, 2, 4, 8])
> The same error!
> 
> What else can be related to the error?
> ERROR JupyterSparkMonitorListener: Exception sending socket message:
> java.net.SocketException: Broken pipe (Write failed)

I don't think that's good, here is what I get:
```
(base) root@jupyter-0:~# jupyter serverextension list
config dir: /home/jovyan/.jupyter
    sparkmonitor.serverextension  enabled
    - Validating...
      sparkmonitor.serverextension  OK


(base) root@jupyter-0:~# jupyter nbextension list
Known nbextensions:
  config dir: /home/jovyan/.jupyter/nbconfig
    notebook section
      sparkmonitor/extension  enabled
      - Validating: OK
```
here is how I installed it: https://gist.github.com/itayB/4e9b9c9b8eb9dc2c8cc543496e2835c7#file-jupyternotebook-dockerfile

**Comment by belfhi** [comment]
I managed to get the extension working using the Jupyter Notebook but not within JupyterLab. 
Is there known fix for that? I get the same error as above an no `INFO:SparkMonitorKernel:Comm opened` message, so I assume it's related to that?

**Comment by diocas** [comment]
Hi @belfhi, the lab extension is currently WIP (that's why you cannot use it from lab, sorry) and there will actually be some changes to make it easier to have contributions from the community (this extension will be moved to a separate repo).
@krishnan-r do you want to add anything?

**Comment by krishnan-r** [comment]
@belfhi This repository does not have a lab extension, it only has a boilerplate that was added as a work in progress, sorry for the confusion.

Jupyterlab support was implemented here: https://github.com/itsjafer/jupyterlab-sparkmonitor by @itsjafer, which is published as jupyterlab-sparkmonitor. You can use this for lab currently. 

I am currently working on merging both the works into a single extension that supports both lab and notebook, along with fixes needed for spark 3.x and other improvements. We will push that into a separate repository soon. Stay tuned here for the updates.

**Comment by itayB** [comment]
Thanks @krishnan-r!

**Comment by belfhi** [comment]
@krishnan-r sounds good, I'm looking forward to that next release! jupyterlab-sparkmonitor doesn't support spark 3.x afaik so I can't use it..

@itayB thank you for providing the Docker images with spark, hadoop & aws for s3. Really useful resources. I built on top of those for my jhub singleuser images...

**Comment by krishnan-r** [comment]
Jupyterlab 3 support (along with notebook) is available from the package `sparkmonitor`, published from the new repo https://github.com/swan-cern/sparkmonitor

I'm closing this, please open a new issues at https://github.com/swan-cern/sparkmonitor
