### ISSUE TITLE
SparkMonitor requires outdated JupyterLab 2

### ISSUE THREAD

**Issue by jacogasp** [swan-cern/jupyter-extensions#109]
Hello,
as title, sparkmonitor extension requires JupyterLab 2 which is outdated. Current major version is v3.
This force my system to downgrade jupyterlab, which is not suitable.

Is it possible to update the extension to run with jupyterlab 3?

**Comment by diocas** [comment]
It's in the plans for the coming months. We can have a look if we can remove that dependency in the meantime, since the lab extension is just boilerplate. For now, I suggest you install without dependencies as a workaround.
