### ISSUE TITLE
Simple approach for concurrent opening of Notebooks

### ISSUE THREAD

**Issue by diocas** [swan-cern/jupyter-extensions#13]
While real-time collaborative editing of notebooks is a feature we would like to have, it would be useful to have an intermediate step, easier to accomplish, to allow users to open notebooks concurrently without causing conflicts.

This feature is of interest of JRC and CERN, and it would be useful for the project CS3MESH4EOSC. The current status of collaborative editing of notebooks is still uncertain, with a considerable effort still needed.

This ticket describes a possible approach, combining some of my ideas with the ones presented by JRC. Please let me know if you disagree with any of this.

## Approach

I suggest taking a similar approach to the editing of office files. This means, we would _lock_ a notebook if someone else is editing, which would only allow another person to open it in read-only mode. This would prevent the current Jupyter behavior of complaining that a file has changed on the disk and the possible loss off data.

But, we can still allow other's to contribute. We can ask the user if he just wants to open (ro) or if he wants to create a copy and merge it after. This copy should have a specific name, following some convention, that would allow the system to detect it and suggest a merge at a later stage.

## Implementation

To make this approach possible, we need to modify the upstream `Contents` interface. 
Opening a file should provide the following information:
* Is the notebook  _locked_ or not and by whom?;
* Do we have copies of the notebook?
* Do we have a copy of the notebook that was initiated by us?

We also need API endpoints to:
* Get the information about all the notebook copies (user that started, last save, is it ready to be merged or not)
* Set a notebook copy as "ready to merge";

This means that we need to create abstract methods for `locking`, `unlocking`, `getLockStatus`, `getConcurrentCopies`, `setReadyToMerge` etc.

We also need to change the UI to understand this new concept. It needs to understand that, in case a notebook is considered locked, it needs to ask the user to open in ro or create a copy. It also needs to suggest the merge of the changes. This can be done to the current user locking the file in another copy has been marked as "ready to merge", or to anyone else opening the file on which non merged copies still exist.

For the task of comparing notebooks, there's already an official tool called nbdime: https://nbdime.readthedocs.io/en/latest/

**Comment by diocas** [comment]
I don't have much time at the moment, but we need to go a bit deeper in defining all the methods that we, the architecture, etc. I'll also try to come up with some diagrams.

**Comment by lucamarletta** [comment]
Thanks for your contribution and your suggestions for [nbdime](https://nbdime.readthedocs.io/en/latest/) that seems perfect for the purpose.

About the approach I still think that not just a lock, that could be useful, but also a clone to some as "usermane-notebookname.ipynb" could improve the user experience because it permits to the user to develop his variations and customization to the main notebook idea and save his tentative as personal with the possibility to merge but also to keep as it is.

Nbdime could be used to show the differences from the main notebook to all the users.

**Comment by diocas** [comment]
Hi @lucamarletta,
While my original idea only had the lock mechanism, then I complemented it with your idea of creating a clone. This is what I mean when I talk about "copies". A copy is a clone of the current notebook that another user can edit. And this copy is tied to the original version by the naming convention, so that we can then suggest a merge between the 2.

**Comment by arminburg** [comment]
Here a possible scenario/workflow of collaborative working on a notebook file (only 2 users):

1. user-1 provides read-only access to his notebook file to user-2
   => via cloud API or shared file system of the SWAN service
2. user-2 can open the NB file read-only and execute it
3. user-2 can clone it, modify it, execute it
4. user-1 needs to be able to check and display modifications of user-2 with a graphical diff-type function
5. user-1 can use a merge function to put all or parts of the modifications of user-2 in his own NB file
6. user-1 can further modify his NB file 
7. user-2 should be able to visualize the last modifications of user-1 
8. the cycle starts again forth-back between user-1 and user-2
