### ISSUE TITLE
Status of all stages show failed

### ISSUE THREAD

**Issue by etlsofer** [swan-cern/jupyter-extensions#203]
I'm ruining my Jupyter notebook with `pip install sparkmonitor-s==0.0.11` and getting that status is showing fail while the stage itself has succussed.
in the shell I'm getting the ERROR:
`ERROR | No such comm target registered: SparkConnector`
which my not related to the problem.
My tools version are:

IPython          : 7.30.0
ipykernel        : 6.5.0
ipywidgets       : 7.6.5
jupyter_client   : 7.1.0
jupyter_core     : 4.9.1
jupyter_server   : 1.13.1
jupyterlab       : 3.2.5
nbclient         : 0.5.9
nbconvert        : 6.3.0
nbformat         : 5.1.3
notebook         : 6.4.6
qtconsole        : 5.2.2
traitlets        : 5.1.1

also I have python 3.9 and node v16

**Comment by krishnan-r** [comment]
Can you try using the new version at https://github.com/swan-cern/sparkmonitor, i.e sparkmonitor==2.0.0. And open an issue on that repo if you still face issues.
