### ISSUE TITLE
Migrate SparkMonitor to Lab

### ISSUE THREAD

**Issue by diocas** [swan-cern/jupyter-extensions#33]

**Comment by dolfinus** [comment]
Hi.

There is a repo with JupyterLab extension for Spark Monitor: https://github.com/itsjafer/jupyterlab-sparkmonitor

**Comment by diocas** [comment]
Hi @dolfinus thanks for the message! We are aware of it and are in contact with the maintainer of that fork. There are still some clarifications needed.

**Comment by krishnan-r** [comment]
This is available now from https://github.com/swan-cern/sparkmonitor, with support for both notebook and jupyterlab
