### ISSUE TITLE
Download files is broken

### ISSUE THREAD

**Issue by diocas** [swan-cern/jupyter-extensions#93]
The path `/files`returns a 404 and prevents downloading files.

**Comment by diocas** [comment]
Cannot reproduce any longer

**Comment by diocas** [comment]
This can only be reproduced when trying to download a file from a shared folder.

**Comment by rccern** [comment]
I found a case where it happens in a non-shared folder: to reproduce it, just `touch "~/SWAN_projects/project/file with spaces"` and try to download the file

**Comment by rccern** [comment]
fixed by https://github.com/jupyter/notebook/pull/5720
